apiVersion: v1
kind: Secret
metadata:
  name: rancher-backup-s3-creds
  namespace: cattle-resources-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  accessKey: YWJjCg==
  secretKey: YWJjCg==
